### ISSUE TITLE
.NET Standard?

### ISSUE THREAD

**Issue by denisz1** [thomasgalliker/Guards#1]
Is this lib supporting .NET Core/Standard?

**Comment by thomasgalliker** [comment]
Guards project includes a PCL assembly which supports .NET Core and .NET Standard. Please let me know if Guards is not supported in your project.

**Comment by denisz1** [comment]
Ha it looks like it is working. I did not know that to be .NET Standard is same as for PCL.

This meaning that your lib is only one so far which is supporting netstandard. Bravo! Others are supporting various PCL profiles but they are not working in netstandard app.

**Comment by thomasgalliker** [comment]
I'm a bit confused too. My understanding of PCL is that it is just an adaptable library that *can* be compatible with .NET Standard/Core depending on which PCL profiles I select. The more profiles I select the more platforms are supported - but the smaller the feature set will be.

Thanks for the flowers. Whenever you see something not working, let me know. Open source software is only successful if people (like you) use it, report bugs, participate. :+1:
