### ISSUE TITLE
Multiple enumerations of IEnumerable

### ISSUE THREAD

**Issue by carlosrfernandez** [thomasgalliker/Guards#7]
Just started checking out the lib. 

A minor issue I see with it is that the `Guard.Enumerable.ArgumentNotNullOrEmpty` method is enumerating the incoming collection. This is a potential problem depending on the use case.

It might be worth adding a message on the method header warning consumers of the API or calling Reset to return the enumerator back to it's original position. 

Another possibility is to actually enumerate to array or list, but that might be a performance hit.

**Comment by thomasgalliker** [comment]
Ok. Thanks for reporting. How easy is it for you to prepare a simple code example which demonstrates the problem? Then, I could use your code to write a unit test and fix the problem. Okay?

**Comment by carlosrfernandez** [comment]
I can possibly create a PR sometime soon.

**Comment by thomasgalliker** [comment]
Hi @carlosrfernandez, I found some time to reproduce this issue. Have a look at this unit test. I create a list of strings. From this list I create an enumerator, loop trough each string and inside each iteration, I go check for ArgumentNotNullOrEmpty of the original string list. 

```
[Fact]
public void ArgumentNotNullOrEmpty_DoesNotThrowIfEnumerableContainsItems()
{
    // Arrange
    var enumerable = new List<string> { "item1", "item2" };
    string argumentName = nameof(enumerable);

    // Act
    var enumerator = enumerable.GetEnumerator();
    while (enumerator.MoveNext())
    {
        Action action = () => Guard.ArgumentNotNullOrEmpty(enumerable, argumentName);

        // Assert
        action.Should().NotThrow<ArgumentException>();
    }
}
```

As far as I unserstand, whenever you call GetEnumerator (which is the case when you pass an IEnumerable to a foreach or call ToList on it), it automatically starts the iteration from the first element - it does not even call Reset() on the previous IEnumerable. 

I think the only drawback of ArgumentNotNullOrEmpty is for unmaterialized database queries. It might calls the database just to run the argument check.

The only way around this is, to remove this guard and add one for ICollection (something that is clearly already materialized).

**Comment by carlosrfernandez** [comment]
@thomasgalliker Apologies for not getting back to you sooner! I've  been swamped with work.

I agree it's not actually producing multiple enumerations, in the few tests I tried, it worked fine, since it's always returning  a new Enumerator.

I'll close this issue. 

Regards!
